# Generated by Django 4.2.2 on 2023-06-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("due_date", models.DateTimeField()),
                ("is_complete", models.BooleanField()),
            ],
            options={
                "ordering": ["is_complete", "-due_date"],
            },
        ),
    ]
